"""Update Character model to use PostgreSQL-specific ARRAY type

Revision ID: 69d7325b0e7f
Revises: b8bfa7a23e9c
Create Date: 2024-06-03 02:06:55.658324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69d7325b0e7f'
down_revision: Union[str, None] = 'b8bfa7a23e9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
