"""change barcode to barcodes

Revision ID: b8bfa7a23e9c
Revises: af809ff3602e
Create Date: 2024-06-03 02:01:44.931225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8bfa7a23e9c'
down_revision: Union[str, None] = 'af809ff3602e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('barcodes', sa.ARRAY(sa.String()), nullable=False))
    op.alter_column('characters', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('characters_barcode_key', 'characters', type_='unique')
    op.drop_column('characters', 'barcode')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('barcode', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint('characters_barcode_key', 'characters', ['barcode'])
    op.alter_column('characters', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('characters', 'barcodes')
    # ### end Alembic commands ###
